version: "3.8"
services:
  db:
    image: mariadb:10.6.4
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "5306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: {}
